network:
  protocol: http
  interface: 0.0.0.0
  websocket_port: 6901
  ssl:
    pem_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
    pem_key: /etc/ssl/private/ssl-cert-snakeoil.key
    require_ssl: true

desktop:
  resolution:
    width: 1920
    height: 1080
  allow_resize: true
  pixel_depth: 24

user_session:
  idle_timeout: never

keyboard:
  raw_keyboard: true
  ignore_numlock: true

server:
  http:
    httpd_directory: /usr/share/kasmvnc/www
  advanced:
    kasm_password_file: ${HOME}/.kasmpasswd

data_loss_prevention:
  clipboard:
    server_to_client:
      enabled: true
    client_to_server:
      enabled: true

encoding:
  max_frame_rate: 30
